### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by yuretzgt** [smeyanoff/car-number-detection#20]
Не хватает модуля
ultralytics

PS: можно ли распознать номер с фото?

**Comment by smeyanoff** [comment]
Сделайте PR

Да, можно фото.

**Comment by kut666** [comment]
Добрый вечер, кажется при установке torch из requirements.txt виртуалка просто зависает, приходится насильно завершать установку либ. Я один сталкиваюсь с подобным, как такое можно решить?

**Comment by vash-sa** [comment]
Привет. Запускаю на виртуалке с Linux. Дает следующую ошибку. Можешь объяснить?
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.

**Comment by smeyanoff** [comment]
> Добрый вечер, кажется при установке torch из requirements.txt виртуалка просто зависает, приходится насильно завершать установку либ. Я один сталкиваюсь с подобным, как такое можно решить?

Может vpn или вроде того, какая ошибка?

**Comment by smeyanoff** [comment]
> Привет. Запускаю на виртуалке с Linux. Дает следующую ошибку. Можешь объяснить? RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.

В этом [файлике](https://github.com/smeyanoff/car-number-detection/blob/main/settings.py) DEVICE = 'cpu' попробуйте поставить. Похоже нет gpu в Вашем компьютере.

**Comment by smeyanoff** [comment]
Закрываю этот тред, открывайте новые, пожалуйста.
